
// ** CREATE SESSION **
export const SESSION_CREATE_START = 'SESSION_CREATE_START';
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAIL = 'SESSION_CREATE_FAIL';

export const USER_CREATE_START = 'USER_CREATE_START';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

// ** VALIDATE TOKEN **
export const VALIDATE_START = 'TOKEN_VALIDATE_START';
export const VALIDATE_SUCCESS = 'TOKEN_VALIDATE_SUCCESS';
export const VALIDATE_FAIL = 'TOKEN_VALIDATE_FAIL';