

export const account = {
    // CHECK
    CHECK: 'ACCOUNT_CHECK',
    CHECK_PENDING: 'ACCOUNT_CHECK_PENDING',
    CHECK_FULFILLED: 'ACCOUNT_CHECK_FULFILLED',
    CHECK_REJECTED: 'ACCOUNT_CHECK_REJECTED',

    // CREATE
    CREATE: 'ACCOUNT_CREATE',
    CREATE_PENDING: 'ACCOUNT_CREATE_PENDING',
    CREATE_FULFILLED: 'ACCOUNT_CREATE_FULFILLED',
    CREATE_REJECTED: 'ACCOUNT_CREATE_REJECTED',

    // SIGN IN
    SIGNIN: 'ACCOUNT_SIGNIN',
    SIGNIN_PENDING: 'ACCOUNT_SIGNIN_PENDING',
    SIGNIN_FULFILLED: 'ACCOUNT_SIGNIN_FULFILLED',
    SIGNIN_REJECTED: 'ACCOUNT_SIGNIN_REJECTED',

    // SIGN OUT
    SIGNOUT: 'ACCOUNG_SIGNOUT',


}