

export const account = {
    // CHECK
    CHECK: 'ACCOUNT_CHECK',
    CHECK_PENDING: 'ACCOUNT_CHECK_PENDING',
    CHECK_FULFILLED: 'ACCOUNT_CHECK_FULFILLED',
    CHECK_REJECTED: 'ACCOUNT_CHECK_REJECTED',

    // CREATE
    CREATE: 'ACCOUNT_CREATE',
    CREATE_PENDING: 'ACCOUNT_CREATE_PENDING',
    CREATE_FULFILLED: 'ACCOUNT_CREATE_FULFILLED',
    CREATE_REJECTED: 'ACCOUNT_CREATE_REJECTED',

    // SIGN IN
    SIGNIN: 'ACCOUNT_SIGNIN',
    SIGNIN_PENDING: 'ACCOUNT_SIGNIN_PENDING',
    SIGNIN_FULFILLED: 'ACCOUNT_SIGNIN_FULFILLED',
    SIGNIN_REJECTED: 'ACCOUNT_SIGNIN_REJECTED',

    // SIGN OUT
    SIGNOUT: 'ACCOUNT_SIGNOUT',


}

export const stock = {
    // GET ONE DAY
    GET_ONE_DAY: 'STOCK_GET_ONE_DAY',
    GET_ONE_DAY_PENDING: 'STOCK_GET_ONE_DAY_PENDING',
    GET_ONE_DAY_FULFILLED: 'STOCK_GET_ONE_DAY_FULFILLED',
    GET_ONE_DAY_REJECTED: 'STOCK_GET_ONE_DAY_REJECTED',

    // GET FIVE YEARS
    GET_FIVE_YEARS: 'STOCK_GET_FIVE_YEARS',
    GET_FIVE_YEARS_PENDING: 'STOCK_GET_FIVE_YEARS_PENDING',
    GET_FIVE_YEARS_FULFILLED: 'STOCK_GET_FIVE_YEARS_FULFILLED',
    GET_FIVE_YEARS_REJECTED: 'STOCK_GET_FIVE_YEARS_REJECTED',
}
